# Application name
spring.application.name=expensetracker

# PostgreSQL Datasource (Render)
spring.datasource.url=jdbc:postgresql://dpg-d6gs5mi4d50c73eug510-a:5432/moneytracker_db_7g88
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=moneytracker_db_7g88_user
spring.datasource.password=NixzYHfzEJfgokBvTlau03G6DFnPOApa

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# H2 console is not needed
# spring.h2.console.enabled=true
